### PR TITLE
Add TLS spec to Ingress

### PR DESCRIPTION
**Pull request by ccremer**
* Adds TLS spec to Ingress

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Update the documentation.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.

### CODE REVIEW

**Comment by ccremer** [comment]
Question: Currently it's assumed that the TLS secret is provisioned by cert-manager. Should we add functionality to manage secrets, e.g. to be able to provision commercial certificates?

**Comment by tobru** [comment]
> Should we add functionality to manage secrets, e.g. to be able to provision commercial certificates?

I don't think that this is needed atm, we're using LE all over the place...

**Comment by ccremer** [comment]
Fine by me, however we should then clearly state that cert-manager is required and maybe even make the cert-manager annotation a default value?

**Comment by tobru** [comment]
Yes :+1:

**Review by bastjan — APPROVED** [review]

**Pull request merged**
